#!/bin/zsh

# zsh profile file. Runs on login. Environmental variables are set here.

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="qutebrowser"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export IPYTHONDIR="${XDG_CONFIG_HOME}/ipython"

typeset -U PATH path  # Remove duplicates from PATH
path=("$HOME/.bin" "$path[@]")  # Custom executables
path=("$HOME/.local/bin" "$path[@]")  # pipx executables
path=("$HOME/.pyenv/bin" "$path[@]")
path=("$HOME/.config/scripts" "$path[@]")
export PATH

[ -f $ZDOTDIR/secrets ] && source $ZDOTDIR/secrets

if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]; then
    . ${HOME}/.nix-profile/etc/profile.d/nix.sh
fi

# Start graphical server on tty1 if not already running.
# The ardelay and arinterval options set the key repeat delay and rate in milliseconds
[ "$(tty)" = "/dev/tty1" ] && ! pidof Xorg >/dev/null 2>&1  && exec startx -- -ardelay 230 -arinterval 20
