#! /usr/bin/bash
# vim: ft=sh

sudo add-apt-repository ppa:regolith-linux/release
sudo apt-get update

sudo apt install \
    i3-gaps-wm \
    dunst \
    i3lock \
    autorandr \
    rofi \
    unclutter-xfixes \
    network-manager-gnome \
    xinit \
    tree \
    apt-file \
    curl \
    git \
    tmux \
    qutebrowser

wget "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M/Regular/complete/Meslo LG M Regular Nerd Font Complete Mono.ttf"
