#!/usr/bin/bash
# vim: ft=sh

install_pack=$(which install_archlinux)

###
# Find native explicitly installed packages that are not listed in $install_pack
###

# All explicitly installed native packages
pacman -Qneq | sort > /tmp/all.txt

# All explicitly installed native packages that were in fact installed as part of a group
rm -f /tmp/group.tmp
groups=$(cat $install_pack | grep '(group)$' | awk '{print $1}')
for group in $groups; do
	pacman -Qgq $group >> /tmp/group.tmp
done
cat /tmp/group.tmp | sort > /tmp/group.txt

# Individually installed packages is the difference between the two files
comm -23 /tmp/all.txt /tmp/group.txt > /tmp/ind.txt

# Individually installed native packages listed in $install_pack
cat $install_pack | grep '^    [a-zA-Z][^ ]' | grep -v '(aur)$' | grep -v '(group)$' | grep -v ' dep of ' | awk '{print $1}' | sort > /tmp/ind_listed.txt

echo "Native packages:"
echo "The following packages are installed but not listed in $install_pack:"
comm -23 /tmp/ind{,_listed}.txt
echo
echo "The following packages are listed in $install_pack but not installed:"
comm -13 /tmp/ind{,_listed}.txt
echo

# Cleanup
rm /tmp/all.txt /tmp/group.txt /tmp/group.tmp /tmp/ind{,_listed}.txt


###
# Find external explicitly installed packages that are not listed in $install_pack
###

# All explicitly installed external packages
pacman -Qmeq | sort > /tmp/all.txt

# Installed external packages listed in $install_pack
cat $install_pack | grep '(aur)$' | awk '{print $1}' | sort > /tmp/listed.txt

echo "External packages (AUR):"
echo "The following packages are installed but not listed in $install_pack:"
comm -23 /tmp/all.txt /tmp/listed.txt
echo
echo "The following packages are listed in $install_pack but not installed:"
comm -13 /tmp/all.txt /tmp/listed.txt
echo

# Cleanup
rm /tmp/all.txt /tmp/listed.txt
