#! /bin/bash

if [[ "$1" = "wifi" ]]; then
    state=$(nmcli radio wifi)
    if [[ "$state" = "enabled" ]]; then
        nmcli radio wifi off
    else
        nmcli radio wifi on
    fi
elif [[ "$1" = "vpn" ]]; then
    vpn_line=$(nmcli --fields type,name,active connection show | grep '^vpn')

    connection_name=$(echo $vpn_line | awk '{print $2}')
    connection_active=$(echo $vpn_line | awk '{print $3}')

    if [[ "$connection_active" = "no" ]]; then
        nmcli connection up $connection_name
    else
        nmcli connection down $connection_name
    fi
elif [[ "$1" = "bluetooth" ]]; then
    if bluetoothctl show | grep -q "Powered: yes"; then
        bluetoothctl power off
    else
        bluetoothctl power on
    fi
fi
