#!/bin/bash

# This script is used to add some custom keymaps on top of the us(altgr-intl)
# (see ~/.config/xkb/symbols/glostis for the actual keymaps)
# The setxkbmap -print | sed > file; xkbcomp file was taken from two sources:
# - https://web.archive.org/web/20170825051821/http://madduck.net/docs/extending-xkb/
# - https://www.vinc17.net/unix/xkb.fr.html
#
# It is executed on X startup in ~/.xinitrc, and on keyboard plug/unplug in ~/.config/xplugrc
#
# Note: according to http://who-t.blogspot.com/2020/02/user-specific-xkb-configuration-part-1.html,
# this process could be made easier by libxkbcommon, but it is used by Wayland, not X...

kb_layout=$1
kb_type=$2

if [ "$kb_layout" = "us" ]; then
    symbols_options="+glostis(hacks)"
    if [ "$kb_type" = "kinesis" ]; then
        symbols_options="${symbols_options}+glostis(kinesis)"
    fi
    # -option compose:ralt is needed to play nice with kmonad
    setxkbmap -layout 'us(altgr-intl),fr' -print | \
    sed -e "/xkb_symbols/s/\"[[:space:]]/${symbols_options}&/" > $HOME/.config/xkb/map
    xkbcomp -I$HOME/.config/xkb $HOME/.config/xkb/map $DISPLAY

    pgrep kmonad || kmonad ${HOME}/.config/kmonad/config.kbd &

elif [ "$kb_layout" = "fr" ]; then
    setxkbmap -layout 'fr'

    killall kmonad
else
    echo Keyboard layout ${kb_layout} not known
    exit 2
fi

xset r rate 230 50
