#!/bin/bash

# This script is used to add some custom keymaps on top of the us(altgr-intl)
# (see ~/.config/xkb/symbols/glostis for the actual keymaps)
# The setxkbmap -print | sed > file; xkbcomp file was taken from two sources:
# - https://web.archive.org/web/20170825051821/http://madduck.net/docs/extending-xkb/
# - https://www.vinc17.net/unix/xkb.fr.html
#
# It is executed on X startup in ~/.xinitrc, and on keyboard plug/unplug in ~/.config/xplugrc
#
# Note: according to http://who-t.blogspot.com/2020/02/user-specific-xkb-configuration-part-1.html,
# this process could be made easier by libxkbcommon, but it is used by Wayland, not X...

if [ -f $HOME/.config/xkb/symbols/glostis ]; then
    symbols_options="+glostis(french_accents)"
    if [ "$1" = "kinesis" ]; then
        symbols_options="${symbols_options}+glostis(kinesis)"
    fi
    setxkbmap -layout 'us(altgr-intl),fr' -option 'caps:swapescape' -print | \
    sed -e "/xkb_symbols/s/\"[[:space:]]/${symbols_options}&/" > $HOME/.config/xkb/map
    xkbcomp -I$HOME/.config/xkb $HOME/.config/xkb/map $DISPLAY
fi

xset r rate 230 50
