#!/bin/sh

# This script is called whenever a new device (mouse, keyboard, monitor) is connected
# or disconnected.
#
# The arguments look like:
# xplugrc TYPE DEVICE STATUS ["Optional Description"]
#          |    |      |
#          |    |       `---- connected or disconnected
#          |     `----------- HDMI3, LVDS1, VGA1, etc.
#           `---------------- keyboard, pointer, display

# FYI: udev sees Bluetooth headsets and some mice as keyboards...
# So when a Bluetooth headset or mouse is {,dis}connected, it triggers
# an xplug event with device=keyboard
if [ "$1" = "keyboard" ]; then
    nb_kinesis=$(find /dev/input/by-id/ -name 'usb-Kinesis_Advantage2_Keyboard*' | wc -l)
    if [ "$nb_kinesis" -gt 0 ]; then
        kb_type="kinesis"
    else
        kb_type="laptop"
    fi
    "$HOME"/.bin/custom_keyboard_layout $kb_type
fi

if [ "$1" = "display" ]; then
    autorandr --change
fi
