user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.compactmode.show", true);
user_pref("browser.formfill.enable", false);
user_pref("browser.overlink-delay", 0);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.page", 3);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.ctrlTab.sortByRecentlyUsed");
user_pref("browser.uidensity", 1);
user_pref("browser.display.use_system_colors", true);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("intl.accept_languages", "fr-fr,en-us,en");
// user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);
user_pref("permissions.default.xr", 2);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("widget.content.allow-gtk-dark-theme", true);
