# vim: filetype=zsh


eval "$(pyenv init --path)"

[ -f $ZDOTDIR/secrets ] && source $ZDOTDIR/secrets

HISTFILE=~/.cache/zsh/history
mkdir -p $(dirname $HISTFILE)
HISTSIZE=100000
SAVEHIST=100000
bindkey -e

setopt autocd       # Automatically cd into typed directory.
stty stop undef     # Disable ctrl-s to freeze terminal.

autoload -Uz compinit

# Highlight selected completion in the list
zstyle ':completion:*' menu select

# Source: https://superuser.com/a/815317
# 0 -- vanilla completion (abc => abc)
# 1 -- smart case completion (abc => Abc)
# 2 -- word flex completion (abc => A-big-Car)
# 3 -- full flex completion (abc => ABraCadabra)
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'
zmodload zsh/complist
compinit
_comp_options+=(globdots)  # Include hidden files.

if [ -f "$HOME/.zsh_plugins.sh" ]; then
    source $HOME/.zsh_plugins.sh
else
    echo "Bundling zsh plugins..."
    antibody bundle < $HOME/.config/zsh/plugins.txt > $HOME/.zsh_plugins.sh
fi

# This shows a squiggly character in green if the previous return code
# was zero (success) or in red if the previous return code was non-zero (failure)
function return_code() {
    case "$HOST" in
        gaston*)
            prompt_char="ᰜ"
        ;;
        fr-glostis-g3*)
            prompt_char="ξ"
        ;;
        *)
            prompt_char="?"
        ;;
    esac
    echo "%(?:%F{green}${prompt_char}%f:%F{red}${prompt_char}%f)"
}

function pyenv_venv() {
    if [[ -n $PYENV_SHELL ]]; then
        local version
        version=$(pyenv version-name)
        if [[ $version != system ]]; then
            echo "($version) "
        fi
    fi
}
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export ZSH_THEME_GIT_PROMPT_PREFIX="("
export ZSH_THEME_GIT_PROMPT_SUFFIX=") "
PROMPT='$(pyenv_venv)$(return_code) %B%F{blue}%c%f%b $(git_super_status)'

[ -n "$RANGER_LEVEL" ] && PROMPT="(ranger) $PROMPT"

[ -f "/usr/share/fzf/key-bindings.zsh" ] && source "/usr/share/fzf/key-bindings.zsh"
[ -f "/usr/share/fzf/completion.zsh" ] && source "/usr/share/fzf/completion.zsh"
export FZF_DEFAULT_COMMAND="rg --files --hidden -g '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

source ${ZDOTDIR}/zbindings
source ${ZDOTDIR}/zalias
source ${ZDOTDIR}/zfunctions

eval "$(pyenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
