name        = "glostis-colemak"
name8       = "glostis-colemak"
locale      = "us"
variant     = "hack"
author      = "glostis"
description = "Custom Colemak layout adapted for coding and writing in French"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "0.0.1"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃ €   │ «   │ »   │     │     ┃     │     │     │     │     ┃ _   ┆ +   ┆
┆ `   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ 0 ° ┃ -   ┆ =   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ W   │ F   │ P   │ B   ┃ J   │ L   │ O   │ !   │ Y   ┃ {   ┆ }   ┆
·     ┃   œ │     │   à │   ù │     ┃     │     │   ô │**   │   î ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ R   │ S   │ T   │ G   ┃ H   │ N   │ E   │ I   │ U   ┃ "   ┆ |   ┆
·     ┃   â │   é │   è │     │     ┃   ( │   ) │   ê │     │   û ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ Z   │ X   │ C   │ D   │ V   ┃ K   │ M   │ ;   │ :   │ ?   ┃           ·
┆ <   ┃     │     │   ç │   _ │     ┃   ← │   → │ ,   │ . … │ - — ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │   × │     │     ┃     ┆     ┆
·     ┃   ^ │   < │   > │   $ │   % ┃   @ │   & │   * │     │     ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   / │   | ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   ` │     │     │     │     ┃     │     │     │   . │     ┃           ·
┆     ┃   ~ │   [ │   ] │   _ │   # ┃   « │   » │     │   . │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
# shift       = "\u0020"  # SPACE
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u202f"  # NARROW NO-BREAK SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK
