#! /bin/bash

if [ $# -eq 0 ]; then
    filename="${HOME}/Pictures/$(date +%Y-%m-%d_%H-%M-%S).png"

    # Takes a screenshot (by clicking on window or dragging an area of screen), saves it to file,
    # and copies it into the clipboard.
    maim --select --hidecursor --nokeyboard $filename
    xclip -selection clipboard -t image/png $filename
else
    # Takes a screenshot of the whole screen and saves it to file
    # This is used for the lock screen
    filename=$1
    maim --hidecursor $filename
fi

