#!/usr/bin/env bash

theme_variant=$(cat ~/.config/alacritty/alacritty.yml | grep '^colors:' | cut -d- -f2)

# GTK_THEME is used to make sure that the Tree Style Tab addon gets the correct dark/light color
# cf https://github.com/piroor/treestyletab/blob/34f353c5eca4906b378f00b2951bd21e09ef0037/README.md#appearance
# MOZ_USE_XINPUT2 is used to enable pixel-perfect trackpad scrolling
# cf https://wiki.archlinux.org/title/Firefox/Tweaks#Pixel-perfect_trackpad_scrolling
GTK_THEME="Adwaita:${theme_variant}" MOZ_USE_XINPUT2=1 firefox -P $1
