#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode
set -euo pipefail
IFS=$'\n\t'

# This script is used to add some custom keymaps on top of the us(altgr-intl)
# (see ~/.config/xkb/symbols/glostis for the actual keymaps)
# The setxkbmap -print | sed > file; xkbcomp file was taken from two sources:
# - https://web.archive.org/web/20170825051821/http://madduck.net/docs/extending-xkb/
# - https://www.vinc17.net/unix/xkb.fr.html
#
# It is executed on X startup in ~/.xinitrc, and on keyboard plug/unplug in ~/.config/xplugrc
#
# Note: according to http://who-t.blogspot.com/2020/02/user-specific-xkb-configuration-part-1.html,
# this process could be made easier by libxkbcommon, but it is used by Wayland, not X...

kb_type=$1

# Sleep to avoid having endless "enter/return" when starting kmonad by hand
sleep 2

if [ "$kb_type" = "kinesis" ]; then
    symbols_options="+glostis-colemak(baguette)"
    pgrep -af 'kmonad*.kinesis' || kmonad ${HOME}/.config/kmonad/kinesis.kbd &
else
    symbols_options="+glostis-qwerty(baguette)"
fi
pgrep -af 'kmonad.*laptop' || kmonad ${HOME}/.config/kmonad/laptop.kbd &

echo "Launched kmonad"

sleep 1

setxkbmap -layout 'us(altgr-intl)' -print | \
sed -e "/xkb_symbols/s/\"[[:space:]]/${symbols_options}&/" > $HOME/.config/xkb/map
# `-w 0` disables all warnings because `xkbcomp` is very verbose
# Remove if need to debug
xkbcomp -I$HOME/.config/xkb -w 0 $HOME/.config/xkb/map $DISPLAY

echo "Launched xkbcomp"

xset r rate 230 50

echo "Launched xset rate"
