#!/bin/sh

# This script is called whenever a new device (mouse, keyboard, monitor) is connected
# or disconnected.
#
# The arguments look like:
# xplugrc TYPE DEVICE STATUS ["Optional Description"]
#          |    |      |
#          |    |       `---- connected or disconnected
#          |     `----------- HDMI3, LVDS1, VGA1, etc.
#           `---------------- keyboard, pointer, display

if [ "$1" = "keyboard" ]; then
    custom_keyboard_layout  # This is a script from ~/.bin
fi
