#!/bin/sh

# This script is called whenever a new device (mouse, keyboard, monitor) is connected
# or disconnected.
#
# The arguments look like:
# xplugrc TYPE DEVICE STATUS ["Optional Description"]
#          |    |      |
#          |    |       `---- connected or disconnected
#          |     `----------- HDMI3, LVDS1, VGA1, etc.
#           `---------------- keyboard, pointer, display

# FYI: xplugd sees Bluetooth headsets as keyboards...
# So when a Bluetooth headset is {,dis}connected, it triggers
# an xplug event with device=keyboard
if [ "$1" = "keyboard" ]; then
    # For some reason, I can't manage to get xplugrc to source my zsh PATH, which includes ~/.bin...
    case "$3,$4" in
        "connected","Kinesis Advantage2"*)
            kb_type="kinesis"
            ;;
    esac
    ${HOME}/.bin/custom_keyboard_layout us ${kb_type}
fi
